### ISSUE TITLE
ServicePointID

### ISSUE THREAD

**Issue by parkstraat9** [onetoweb/transsmart#1]
Hello, 

I am using this code for a while and it works great. 
But now I am running to a problem, I like to send packages to a ServicePoint. 

I try adding: 

    'locations' => [[
        'servicePointId'=> 'NL-123456',
    ]],	

and

    'servicePointId'=> 'NL-123456',

but it does not add a servicepoint id to the Shipment. 
Where do I need to put the ServicepointId?

kind regards peter.

**Comment by loki84nl** [comment]
You can add a service point under additional references with type SERVICEPOINT

```
$response = $client->bookShipment([[
    'additionalReferences' => [[
        'type' => 'SERVICEPOINT',
        'value' => 'NL-123456',
    ]],
]], 'PRINT');
```

**Comment by parkstraat9** [comment]
Ah Great that works !!

Thanks for the fast reply
